# docker-compose.yml
services:
  pdf-engine:
    image: my-pdf-engine:latest
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - API_PORT=${API_PORT}
      - STORAGE_BUCKET=${STORAGE_BUCKET}
      - STORAGE_URL=${STORAGE_URL}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
      - STORAGE_SECRET_KEY=${STORAGE_SECRET_KEY}
      - STORAGE_REGION=${STORAGE_REGION}
      - API_BEARER_TOKEN=${API_BEARER_TOKEN}
    restart: unless-stopped
